name: 'Validate Terraform formating'

on: [push, workflow_dispatch]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  
    defaults:
      run:
        shell: bash
        working-directory: ./Test
  
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: az login
      run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
    
    - name: set IP  into SA  
      run: az storage account network-rule add --account-name challengetestsa --ip-address ${{ steps.ip.outputs.ipv4 }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ secrets.TERRAFORM_VERSION }}

    - name: Show Terraform version
      id: version
      run: terraform version
      

    - name: Terraform init
      id: init
      run: terraform init
    
    - name: Terraform format
      id: fmt
      run: terraform fmt -check -recursive

    - name: Terraform validate
      id: validate
      if: (success() || failure())
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve



