name: 'Validate Terraform formating'

on: [push, workflow_dispatch]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
  
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ secrets.TERRAFORM_VERSION }}

    - name: Show Terraform version
      id: version
      run: terraform version
      

    - name: Terraform init
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: terraform init
    
    - name: Terraform format
      id: fmt
      run: terraform fmt -check -recursive

    - name: Terraform validate
      id: validate
      if: (success() || failure())
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve


